-- Options are automatically loaded before lazy.nvim startup
-- Default options that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua
-- Add any additional options here
vim.opt.winbar = "%=%m %f"

-- require("lua/plugins/toggleterm").setup({
--   size = 20,
--   open_mapping = [[<c-\>]],
--   hide_numbers = true,
--   shade_filetypes = {},
--   shade_terminals = true,
--   shading_factor = 2,
--   start_in_insert = true,
--   insert_mappings = true,
--   persist_size = true,
--   direction = "horizontal",
--   -- close_on_exit = true,
--   shell = vim.o.shell,
--   float_opts = {
--     border = "curved",
--     winblend = 0,
--     highlights = {
--       border = "Normal",
--       background = "Normal",
--     },
--   },
-- })
--
-- function _G.set_terminal_keymaps()
--   local opts = { noremap = true }
--   vim.api.nvim_buf_set_keymap(0, "t", "<esc>", [[<C-\><C-n>]], opts)
--   vim.api.nvim_buf_set_keymap(0, "t", "jk", [[<C-\><C-n>]], opts)
--   vim.api.nvim_buf_set_keymap(0, "t", "<C-h>", [[<C-\><C-n><C-W>h]], opts)
--   vim.api.nvim_buf_set_keymap(0, "t", "<C-j>", [[<C-\><C-n><C-W>j]], opts)
--   vim.api.nvim_buf_set_keymap(0, "t", "<C-k>", [[<C-\><C-n><C-W>k]], opts)
--   vim.api.nvim_buf_set_keymap(0, "t", "<C-l>", [[<C-\><C-n><C-W>l]], opts)
-- end
--
-- vim.cmd("autocmd! TermOpen term://* lua set_terminal_keymaps()")
-- -- Set the keybinding for toggling the terminal
